from flask import Flask, jsonify, request

app = Flask(__name__)

# Data for the units
units_data = {
    "Shadow Of Afton": "4k",
    "Master Puppeteer": "800-1k",
    "Limitless Shadow": "1k",
    "Agonized Springtrap": "4.5k",
    "Fractured Bonnie": "1.5k-2k",
    "RWQFSFASXC": "4.5k",
    "Valkyrie Prime": "55k",
    "Nautic Crusher Mangle": "30k",
    "Animdude": "4k",
    "Bomber Boy": "2k",
    "Fortified Endo 02": "8k-10k",
    "Overclocked Puppeteer": "10k",
    "Deadeye Freddy": "21k-22k",
    "President Freddy": "2k-2.5k",
    "Overseer Foxy": "12k-12.5k",
    "Frostbite Freddy": "75k-80k",
    "Astral Bonnie": "60k+",
    "Old Man Consequences": "90k-100k",
    "Gravelord Foxy": "45k",
    "Kronos Endo Freddy": "50k+",
    "Dark Knight Puppet": "700k+",
    "Black Ice Freddy": "15k-16k",
    "Old Man Krampus": "200k",
    "Dark Frostbear": "20k-25k",
    "Blighted Endo Freddy": "20k+",
    "Leviathan Mangle": "35k+",
    "Phantom Mangle": "4k",
    "Valkyrie Chica": "40k+",
    "Marionette's Puppeteer": "200",
    "Bounded Shadow": "200-300",
    "Springtrap": "7k-8k+",
    "Circuit Breaker Freddy": "300",
    "Glitched Puppeteer": "8k",
    "Nightmarionette": "4k",
    "Nightmare Mangle": "4k",
    "Galleon Foxy": "4.5k-5k",
    "Goliath Endo Freddy": "8k-9k",
    "Outlaw Freddy": "17k",
    "Ennard": "2k-2.5k",
    "It's Me": "10",
    "Endo 05": "3k-3.5k",
    "Dreadbear": "300",
    "Scarecrow Foxy": "2k",
    "Blighted Endo Bonnie": "1.5k",
    "Juggernaut Bonnie": "8k-9k",
    "Scraptrap": "4k",
    "Lefty": "2k",
    "Shadow Bonnie": "10k+",
    "Stonetrap": "1.5k",
    "Diver Endo": "3k",
    "Widow Baby": "2.5k",
    "The King": "2k",
    "Icetrap": "2.5k",
    "Jolly Shadow Bonnie": "500-800",
    "Bouncer": "5k",
    "Overlord Scott": "3.5k",
    "Winter Soldier Bonnie": "200",
    "Moondrop": "20k-30k+",
    "Exotic Butters": "250k-300k",
    "Stardrop": "4k-5k",
    "Withered Bonnie": "1.2k-1.5k",
    "Plane Boy": "2k+",
    "Endo 02": "7.5k+",
    "Pirate Withered Foxy": "500",
    "Rockin Bonnie": "2k",
    "Rad Freddy": "300",
    "Algae Fredbear": "1k+",
    "Withered Golden Freddy": "2K",
    "Spring Bonnie": "150",
    "Phantom Puppet": "350-400",
    "Phantom Cupcake": "50-70",
    "Phantom Balloon Boy": "200-250",
    "Seven Seas Foxy": "2K+",
    "The Crying Child": "300-400",
    "Nightmare Bonnie": "200-250",
    "Freddle": "500",
    "Nightmare Fredbear": "750-850",
    "Fredbear": "100",
    "Nightmare": "250-350",
    "Endo 04": "50-70",
    "Rave Demon Bonnie": "150-200",
    "Hydra Mangle": "350-400",
    "Purple Guy": "800",
    "Jackpot Freddy": "150-200",
    "Bounty Mangle": "1k+",
    "Slick Bonnie": "300-350",
    "Gunslinger Endo": "2.5k",
    "Blindeye Foxy": "350-400",
    "Flame Empress Chica": "20k",
    "Phone Guy": "800-900",
    "Reactor Freddy": "20k",
    "Circus Baby": "200-250",
    "Music Man": "200",
    "Mendo": "550",
    "Tangle": "100",
    "Lolbit": "7k-9k",
    "Elizabeth": "400",
    "Fazbear Mafia": "300-400",
    "Jack O Endo": "35-50",
    "Grimm Foxy": "150-200",
    "Clowntrap": "800",
    "Jack O Cannon": "250",
    "Eclipse Ballora": "4.5k+",
    "Super Freddy": "200-350",
    "Nightguard Afton": "800-1k",
    "Rockstar Foxy": "300",
    "Helpy": "500-700",
    "Security Puppet": "200",
    "Molten Freddy": "400-500",
    "Bucket Bob": "500",
    "Scrap Baby": "4k-5k",
    "Jar Of Pickles": "250k+",
    "Popstar Chica": "200-400",
    "Steampunk Mangle": "400-500",
    "Duelist Puppet": "600-800",
    "Mechanic Afton": "400-500",
    "Geared Endo": "50-100",
    "Tarnished Fredbear": "800-1k",
    "Gladiator Foxy": "20-30",
    "Reindeer Withered Bonnie": "25-50",
    "Frost Queen Ballora": "1k-1.5k",
    "Freddy Frostbear": "1k",
    "Frost Plushtrap": "20-30",
    "Montgomery Gator": "12k-13k",
    "DJ Music Man": "1.5k",
    "Sunshine": "2k-3k",
    "Wet Floor Bot": "1k+",
}

@app.route("/api/values-api", methods=["GET"])
def get_value():
    unit_name = request.args.get("unit_name")
    if not unit_name:
        return jsonify({"error": "Please provide a unit name."}), 400

    value = units_data.get(unit_name)
    if not value:
        return jsonify({"error": "Unit not found."}), 404

    return jsonify({"unit_name": unit_name, "value": value})

if __name__ == "__main__":
    app.run(debug=True)
